
version: "3.8"

services:

  #  MySQL service
  mysql-db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user-service-blog-platform

  #  App
  user-service-blog-platform:
    depends_on:
      - mysql-db
    image: user-service-blog-platform-image
    ports:
      - "8083:8083"