server:
  port: 8083

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user-service-blog-platform
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    requestHeader: authorization
    secretKey: mySecretKey-mySecretKey-mySecretKey
    validity: 3600 # in seconds
  default-users:
    admin:
      username: admin
      password: admin
